server:
  port: 8081
  error:
    include-message: always
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: banktransactiondb
      #username: xyz
      #password: xyz
microservices:
  person:
    base-url: http://localhost:8083
    base-path: /api/v1
    end-point:
      person: ${microservices.person.base-path}/persons
      person-type: ${microservices.person.base-path}/person-types
  bank-account:
    base-url: http://localhost:8080
    base-path: /api/v1
    end-point:
      bank-account: ${microservices.bank-account.base-path}/bank-accounts
